Added meta tags, title and fevicon
Diyatayal/jovian-careers pull request #1
Opened 2024-04-13 19:01 UTC by Diyatayal

Changes:
-Updated the title tag
-Added images for fevicon and meta banner
-Added meta tags, including OG and Twitter tags
-Added fevicn link tag

Test cases checked

Verified the title showing up

2024-04-13 19:52 UTC, 2411nihalsingh requested changes

2024-04-13 19:52 UTC, 2411nihalsingh commented on reset
> +
areee..what is this chakkar? HTML CSS ?

2024-04-13 19:52 UTC, 2411nihalsingh commented on src/index.html
> -            Jovian-Careers
Make the title a little more Catching

2024-04-13 19:52 UTC, 2411nihalsingh commented on src/index.html
> +    <meta name="twitter:image" content="/jovian_meta.png">
Meta tags are pretty nice bro

2024-04-13 20:44 UTC, merged

2024-04-14 15:01 UTC, Diyatayal commented on src/index.html
> +    <meta name="twitter:image" content="/jovian_meta.png">
Thanks bro